version: 2
jobs:
  build:
    docker:
      - image: adamhathcock/cake-build:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: ./build.sh
workflows:
  version: 2
  build_push:
    jobs:
      - build:
          filters:
            branches:
              only: master